services:
  app:
    build: .
    container_name: ip-pftx-app
    restart: unless-stopped
    ports:
      - "8087:8000"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    volumes:
      - suggestions:/app/data

volumes:
  suggestions:
